[package]
name = "py_active_win"
version = "0.0.1"
authors = ["vrteee <vrteee@github.com>"]
edition = "2021"

[lib]
name = "py_active_win"
crate-type = ["cdylib"]

[dependencies]
active-win-pos-rs = "0.8"

[dependencies.pyo3]
version = "0.17.3"
features = ["extension-module"]
