[package]
name = "py_rust_search"
version = "0.0.1"
authors = ["vrteee <vrteee@github.com>"]
edition = "2021"

[lib]
name = "py_rust_search"
crate-type = ["cdylib"]

[dependencies]
rust_search = "2.0.0"

[dependencies.pyo3]
version = "0.17.3"
features = ["extension-module"]
